### ISSUE TITLE
need tensorflow requirements before installing from pip will work

### ISSUE THREAD

**Issue by jcbyts** [jonmatthis/freemocap#21]
Here's the stack
```
Collecting tensorflow-gpu>=2.0
  Downloading tensorflow_gpu-2.5.0-cp37-cp37m-win_amd64.whl (422.6 MB)
     |█████████                       | 116.1 MB 6.5 kB/s eta 13:08:39ERROR: Exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\http\client.py", line 461, in read
    n = self.readinto(b)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\http\client.py", line 505, in readinto
    n = self.fp.readinto(b)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in _main
    status = self.run(options, args)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\cli\req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\commands\install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 128, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 473, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 367, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_criteria_to_update(candidate)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 203, in _get_criteria_to_update
    name, crit = self._merge_into_criterion(r, parent=candidate)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _merge_into_criterion
    if not criterion.candidates:
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 139, in __bool__
    return bool(self._sequence)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in __bool__
    return any(self)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 129, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 33, in _iter_built
    candidate = func()
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 312, in __init__
    version=version,
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\operations\prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\operations\prepare.py", line 552, in _prepare_linked_requirement
    self.download_dir, hashes
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\operations\prepare.py", line 243, in unpack_url
    hashes=hashes,
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\operations\prepare.py", line 102, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\network\download.py", line 157, in __call__
    for chunk in chunks:
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\cli\progress_bars.py", line 152, in iter
    for x in it:
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_internal\network\utils.py", line 86, in response_chunks
    decode_content=False,
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\ProgramData\Anaconda3\envs\freemocap\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**Comment by jonmatthis** [comment]
Yep - As we talked about (elsewhere), you'll need to get CUDA and CUDNN installed correctly on your machine before this code will run. 

We're working on a version that doesn't have those requiremnts, but that'll take a while!

I'll close this issue now, but feel free to add more context if you get it
